#!/bin/bash
#Author: Rajharini R
#Date: 15/4/2021
#Description: Child script for nexted script
#################################################################################

echo This is child_file
for i in $(seq 1 5)
do 
	echo $i
done
echo "Exiting child file..."
