#!/bin/bash
#Author: Rajharini R
#Date: 15/4/2021
#Description: Parent script for nested scripts
##################################################################################

echo "This is parent file"
echo "Opening child file"
exec ./child_file
complete = $!
wait $complete
echo "closing parent_file..."
