#!/bin/bash
#Author: Rajharini R
#Date: 15/4/2021
#Description: Script to create a directory and add content
##################################################################################

ln -s ./data/sample.txt /tmp/sample.txt
echo Softlink created
