#!/bin/bash
#Author: Rajharini R
#Date: 15/4/2021
#Description: Script to find a file and copy to another location
##################################################################################

cp `find . -name sample.txt` /tmp/found.txt
