#!/bin/bash
#Author: Rajharini R
#Date: 15/4/2021
#Description: Script to change open file limit
##################################################################################

ulimit -n 10000
echo "Open file limit for current session change to 10000"
