#!/bin/bash
#Author: Rajharini R
#Date: 15/4/2021
#Description: Script to create a directory and add content
##################################################################################

sudo useradd -d home/testuser tuser
sudo usermod -a -G testgroup tuser
echo User tuser created and added to testgroup
