#!/bin/bash
#Author: Rajharini R
#Date: 15/4/2021
#Description: Script to create user and add to a group
#User needs to be root
##################################################################################
sudo groupadd testgroup
sudo useradd -m -d /home/testuser tuser
sudo usermod -a -G testgroup tuser
echo User tuser created and added to testgroup
