#!/bin/bash
#Author: Rajharini R
#Date: 15/4/2021
#Description: Script to create a directory and add content
##################################################################################

su -c "umask 0644" tuser
echo Permission for tuser updated
