#!/bin/bash
#Author: Rajharini R
#Date: 15/4/2021
#Description: Script to update umask value for a user
##################################################################################

su -c "umask 0644" tuser
echo Permission for tuser updated
