#!/bin/bash
#Author: Rajharini R
#Date: 12/4/2021
#Description: Script to find the factorial of a number
##################################################################################

echo Enter the number:
read n
fact=1
for i in $(seq 1 $n)
do 
	fact=`expr $fact \* $i`
done
echo The factorial of $n is $ fact
